display:
  default:
    display_options:
      fields:
        year:
          label: Année
        request_number:
          label: 'Numéro de la demande'
        number_of_pages:
          label: 'Nombre de pages'
      title: 'Demande d''accès à l''information informelle dossiers précédemment publiés'
  details:
    display_title: 'Demande d''accès à l''information informelle dossiers précédemment publiés'
