display:
  default:
    display_title: Maître
    display_options:
      exposed_form:
        options:
          submit_button: Appliquer
          reset_button_label: Réinitialiser
          exposed_sorts_label: 'Trier par'
          sort_asc_label: Asc
          sort_desc_label: Desc
      pager:
        options:
          expose:
            items_per_page_label: 'Éléments par page'
            items_per_page_options_all_label: '- Tout -'
            offset_label: Décalage
      fields:
        comment_bulk_form:
          label: 'Formulaire d''opérations en masse de commentaire'
          action_title: Action
        subject:
          label: Title
          separator: ', '
        comment_body:
          label: Commentaire
          separator: ', '
        name:
          label: Auteur
          separator: ', '
        entity_id:
          label: 'Posted in'
          separator: ', '
        changed:
          label: 'Mis à jour'
          separator: ', '
        operations:
          label: 'Liens d''actions'
      filters:
        subject:
          expose:
            label: Title
        combine:
          expose:
            label: 'Nom de l''auteur'
        langcode:
          expose:
            label: Langue
      empty:
        area_text_custom:
          content: 'Aucun commentaire disponible.'
