display:
  default:
    display_options:
      exposed_form:
        options:
          submit_button: Recherche
          reset_button_label: Effacer
          exposed_sorts_label: Trier
      header:
        result:
          content: '<p><strong>@total résultats trouvé(s)</strong></p>'
      fields:
        nothing:
          alter:
            text: "<div class=\"row\">\r\n<div class=\"col-sm-10\"><h2 class=\"h4 mrgn-tp-0 mrgn-bttm-md\">{{ title }}</h2></div>\r\n<div class=\"col-sm-2\"><h2 class=\"h4 mrgn-tp-0 mrgn-bttm-md\">Votes: {{ field_vote_up_down }}</h2></div>\r\n</div>\r\n<p><strong>Description :</strong> {{ body }}</p>\r\n<p><strong>Organisation : </strong> {{ field_organization }}</p>\r\n<p><strong>État : </strong> {{ field_sd_status }}{% if field_sd_status_1 == 'released' %} {{ field_status_link }} {% endif %}</p>\r\n<p><strong>Publié : </strong>{{ created }}</p>\r\n<p><a href=\"/fr/node/{{ nid }}\" class=\"btn btn-sm btn-default\"><span class=\"fa fa-comment\"></span> Commentaire</a></p>"
        field_status_link:
          alter:
            text: "<span class=\"glyphicon glyphicon-cog\" aria-hidden=\"true\"></span> <a href={{ field_status_link__uri }}>Obtenir le jeu de données</a>\r\n"
