display:
  default:
    display_title: Maître
    display_options:
      exposed_form:
        options:
          submit_button: Appliquer
          reset_button_label: Réinitialiser
          exposed_sorts_label: 'Trier par'
      pager:
        options:
          expose:
            items_per_page_label: 'Éléments par page'
            items_per_page_options_all_label: '- Tout -'
            offset_label: Décalage
      fields:
        comment_bulk_form:
          label: 'Formulaire d''opérations en masse de commentaire'
        subject: {  }
        comment_body:
          label: Commentaire
        name:
          label: Auteur
        entity_id: {  }
        changed:
          label: 'Mis à jour'
        operations:
          label: 'Liens d''actions'
      filters:
        subject:
          expose: {  }
        combine:
          expose:
            label: 'Nom de l''auteur'
        langcode:
          expose:
            label: Langue
      empty:
        area_text_custom:
          content: 'Aucun commentaire disponible.'
      header:
        area:
          content:
            value: "<div data-drupal-messages=\"\">\r\n    <div role=\"contentinfo\" aria-label=\"Status message\" class=\"messages messages--warning\">\r\n                  Les commentaires dans le dossier Spam seront automatiquement supprimés après 30 jours.\r\n    </div>\r\n</div>"
            format: full_html
