display:
  default:
    display_options:
      exposed_form:
        options:
          submit_button: Recherche
          exposed_sorts_label: Trier
      pager:
        options:
          tags:
            previous: '‹ précédent'
            next: 'suivant ›'
            first: '« première'
            last: 'dernière »'
      fields:
        date_published:
          label: 'Date de publication '
        date_released:
          label: 'Date de diffusion'
        nothing:
          label: Votez
      header:
        result:
          content: '<p><strong>@total résultats trouvé(s)</strong></p>'
