display:
  recent:
    display_options:
      title: 'Articles récents'
  default:
    display_options:
      exposed_form:
        options:
          submit_button: Appliquer
          reset_button_label: Réinitialiser
          exposed_sorts_label: 'Trier par'
      pager:
        options:
          tags:
            first: '« Premier'
            last: 'Suivant »'
      title: Blogue
  all:
    display_options:
      filters:
        combine:
          expose:
            label: Recherche
      sorts:
        created:
          expose:
            label: 'Rédigé le'
        title:
          expose:
            label: Titre
      header:
        result:
          content: 'Affichage de @start à @end sur @total blogues'
label: Blogue
