display:
  default:
    display_options:
      fields:
        nothing:
          alter:
            text: "{% set value_array = agreement_value|replace({',': '', '$': ''})|striptags|trim|number_format('2', '.', ',')|split('.') %}\r\n<div class=\"row\">\r\n<div class=\"col-sm-8\">\r\n{% if nothing_to_report_fr %}\r\n  <h4 class=\"mrgn-tp-0 mrgn-bttm-sm\">{{ nothing_to_report_fr }}</h4>\r\n{% else %}\r\n  <h4 class=\"mrgn-tp-0 mrgn-bttm-sm\">\r\n    <a href=\"/fr/search/grants/reference/{{ partial_id }}\">{{ recipient_legal_name }}</a>\r\n  </h4>\r\n  <div>{{ recipient_city }}, {{ recipient_country_fr }}</div>\r\n  <div class=\"label label-default\">{{ agreement_type_fr }}</div>\r\n{%endif%}\r\n<p><small><strong>Organisation:</strong> {{ org_name_fr}}</small></p>\r\n</div>\r\n<div class=\"col-sm-4 text-right\">\r\n<span class=\"h3 mrgn-tp-0\">$ {{ value_array[0] }}<sup><strong>,{{ value_array[1] }}</strong></sup></span><br />\r\n<small>{% if nothing_to_report_fr %}{{ quarter_fr }}, {{ date_year }}{% else %}{{ date_clean|trim|date('Y-m-d') }}{% endif %}</small><br />\r\n</div>\r\n</div>"
      header:
        result:
          content: '<p><strong>@total  résultats trouvé(s)</strong></p>'
      exposed_form:
        options:
          submit_button: Recherche
          exposed_sorts_label: Trier
      pager:
        options:
          tags:
            previous: '‹ précédent'
            next: 'suivant ›'
            first: '« première'
            last: 'dernière »'
      filters:
        search_api_fulltext:
          expose:
            label: Recherche
      sorts:
        agreement_value:
          expose:
            label: Valeur
