description: 'Trouver et gérer le contenu.'
display:
  default:
    display_options:
      exposed_form:
        options:
          submit_button: Filtrer
          reset_button_label: Réinitialiser
          exposed_sorts_label: 'Trier par'
          sort_asc_label: Asc
          sort_desc_label: Desc
      pager:
        options:
          tags:
            previous: '‹ Précédent'
            next: 'Suivant ›'
            first: '« Premier'
            last: 'Dernier »'
      fields:
        title:
          label: Titre
        type:
          label: 'Type de contenu'
          separator: ', '
        name:
          label: Auteur
        changed:
          label: 'Mis à jour'
        moderation_state:
          label: 'État de modération'
          separator: ', '
        operations:
          label: Actions
      filters:
        type:
          expose:
            label: 'Type de contenu'
        moderation_state:
          expose:
            label: 'État de modération'
        langcode:
          expose:
            label: Langue
        title:
          expose:
            label: Titre
      empty:
        area_text_custom:
          content: 'Aucun contenu disponible.'
      header:
        result:
          content: 'Affichage de @start à @end sur @total'
    display_title: Maître
  page_1:
    display_options:
      menu:
        title: Contenu
      tab_options:
        title: Contenu
        description: 'Trouver et gérer le contenu'
    display_title: Page
