display:
  default:
    display_options:
      exposed_form:
        options:
          submit_button: Recherche
          reset_button_label: Réinitialiser
          exposed_sorts_label: Trier
      fields:
        title:
          label: 'Titre du jeu de données '
        body:
          label: Description
        field_suggested_dataset_dept:
          label: Organisation
        field_status:
          label: État
        field_vote_up_down:
          label: Votez
      header:
        result:
          content: '<p><strong>@total résultats trouvé(s)</strong></p>'
      title: 'Jeux de données suggérés par les utilisateurs'
      pager:
        options:
          tags:
            first: '‹‹ première'
            last: 'dernière ››'
            previous: '‹ précédent'
            next: 'suivant ›'
          expose:
            items_per_page_label: 'Entrées par page'
