display:
  default:
    display_options:
      fields:
        nothing:
          alter:
            text: "<div class=\"row\">\r\n<div class=\"col-sm-8\">\r\n<h4 class=\"mrgn-tp-0 mrgn-bttm-sm\"><a href=\"/fr/search/wrongdoing/reference/{{ id }}\">{{ findings_conclusions_fr }}</a></h4>\r\n<p><small><strong>Organisation:</strong> {{ org_name_fr}}<br />Numéro de demande : {{ ref_number }}</small></p>\r\n</div>\r\n<div class=\"col-sm-4 text-right\">\r\n<span class=\"h3 mrgn-tp-0\">{{ file_id_number }}</small></sup></span><br />\r\n<small>{{ date_clean }}</small>\r\n</div>\r\n</div>"
      exposed_form:
        options:
          submit_button: Recherche
          exposed_sorts_label: 'Trier par'
      pager:
        options:
          tags:
            previous: '‹ précédent'
            next: 'suivant ›'
            first: '« première'
            last: 'dernière »'
      filters:
        search_api_fulltext:
          expose:
            label: Recherche
      header:
        result:
          content: '<p><strong>@total résultats trouvé(s)</strong></p>'
