display:
  recent:
    display_options:
      title: 'Articles récents'
      use_more_text: plus
  default:
    display_options:
      exposed_form:
        options:
          submit_button: Recherche
          reset_button_label: Réinitialiser
          exposed_sorts_label: Trier
      pager:
        options:
          tags:
            first: '‹‹ première'
            last: 'dernière ››'
            previous: '‹ précédent'
            next: 'suivant ›'
      title: Blogue
      sorts:
        created:
          expose:
            label: Date
  all:
    display_options:
      filters:
        combine:
          expose:
            label: Recherche
      sorts:
        created:
          expose:
            label: Date
        title:
          expose:
            label: Titre
label: Blogue
