display:
  default:
    display_options:
      fields:
        nothing:
          alter:
            text: "<div class=\"row\">\r\n<div class=\"col-sm-8\">\r\n<h2 class=\"h4 mrgn-tp-0\">\r\n{% if nothing_to_report_fr %}\r\n<span class=\"hgl\">{{ nothing_to_report_fr }}</span>\r\n{% else %}\r\n<a href=\"/fr/search/reclassification/reference/{{ id }}\"><span class=\"hgl\">{{ pos_title_fr }}</span></a>\r\n{%endif%}\r\n</h2>\r\n{% if not nothing_to_report_fr %}<p>Poste no. <span class=\"hgl\">{{ pos_number }}</span></p>{%endif%}\r\n<p><small><strong>Organisation :</strong> <span class=\"hgl\">{{ org_name_fr}}</span>\r\n{% if not nothing_to_report_fr %}<br />Ref # <span class=\"hgl\">{{ ref_number }}</span>{%endif%}</small></p>\r\n</div>\r\n<div class=\"col-sm-4 text-right\">\r\n{% if not nothing_to_report_fr %}<span class=\"h3 mrgn-tp-0\"><span class=\"hgl\">{{ old_class_group_code }}-{{ old_class_level }}</span> <span class=\"glyphicon glyphicon-arrow-right\"></span> <span class=\"hgl\">{{ new_class_group_code }}-{{ new_class_level }}</span></span><br />{%endif%}\r\n<small>{% if nothing_to_report_fr %}{{ quarter_fr }}, {{ date_year }}{% else %}{{ date_clean }}{% endif %}</small>\r\n</div>\r\n</div>"
      exposed_form:
        options:
          submit_button: Recherche
          exposed_sorts_label: Trier
          reset_button_label: Effacer
      pager:
        options:
          tags:
            previous: '‹ précédent'
            next: 'suivant ›'
            first: '« première'
            last: 'dernière »'
      filters:
        search_api_fulltext:
          expose:
            label: Recherche
      sorts:
        old_class_group_code:
          expose:
            label: 'Code du groupe'
      header:
        result:
          content: '<p><strong>@total résultats trouvé(s)</strong></p>'
      empty:
        area_text_custom:
          content: "<p><strong>Aucun résultat trouvé.</strong></p> \r\n<p>Veuillez entrer un nouveau mot-clé.</p>\r\n<br/><br/>\r\n"
