display:
  default:
    display_options:
      fields:
        nothing:
          alter:
            text: "<div class=\"row\">\r\n<div class=\"col-sm-8\">\r\n<h4 class=\"mrgn-tp-0 mrgn-bttm-sm\">\r\n{% if nothing_to_report_fr %}\r\n{{ nothing_to_report_fr }}\r\n{% else %}\r\n<a href=\"/fr/search/reclassification/reference/{{ id }}\">{{ pos_title_fr }}</a>\r\n{%endif%}\r\n</h4>\r\n{% if not nothing_to_report_fr %}<p>Poste no. {{ pos_number }}</p>{%endif%}\r\n<p><small><strong>Organisation :</strong> {{ org_name_fr}}\r\n{% if not nothing_to_report_fr %}<br />Ref # {{ ref_number }}{%endif%}</small></p>\r\n</div>\r\n<div class=\"col-sm-4 text-right\">\r\n{% if not nothing_to_report_fr %}<span class=\"h3 mrgn-tp-0\">{{ old_class_group_code }}-{{ old_class_level }} <span class=\"glyphicon glyphicon-arrow-right\"></span> {{ new_class_group_code }}-{{ new_class_level }}</span><br />{%endif%}\r\n<small>{% if nothing_to_report_fr %}{{ quarter_fr }}, {{ date_year }}{% else %}{{ date_clean }}{% endif %}</small>\r\n</div>\r\n</div>"
      exposed_form:
        options:
          submit_button: Recherche
          exposed_sorts_label: Trier
      pager:
        options:
          tags:
            previous: '‹ précédent'
            next: 'suivant ›'
            first: '« première'
            last: 'dernière »'
      filters:
        search_api_fulltext:
          expose:
            label: Recherche
      sorts:
        old_class_group_code:
          expose:
            label: 'Code du groupe'
      header:
        result:
          content: '<p><strong>@total résultats trouvé(s)</strong></p>'
