default_list:
  - Chnlovecomplaints
  - Russiangirldating
  - Russianwomendate
  - Trustedmedications
  - Thornhilljewellery
  - Tuvanbenhtri
  - Hideuri
  - Girlgirlxvideo
  - Bacsilevanminh
  - Cort.as
  - Mewkid.net
  - Bitchute
  - Charmdate
  - Datereviews
  - Oddsexch
  - Porn.cartoons
  - Ukrainianwomen
  - Remmont
  - Verbum
  - Hec.su
  - Femdomspanking
custom_list:
  - Chnlovecomplaints
  - Russiangirldating
  - Russianwomendate
  - Trustedmedications
  - Thornhilljewellery
  - Tuvanbenhtri
  - Hideuri
  - Girlgirlxvideo
  - Bacsilevanminh
  - Cort.as
  - Mewkid.net
  - Bitchute
  - Charmdate
  - Datereviews
  - Oddsexch
  - Porn.cartoons
  - Ukrainianwomen
  - Remmont
  - Verbum
  - Hec.su
  - Femdomspanking
  - Amoxil
  - mewkid
  - Xandra
  - 'http://baclofen.us.com/]baclofen'
  - 'http://anafranil.us.com/]buy'
  - 'http://phenergan.us.com/]phenergan'
  - 'http://tadalafil247.com/]buy'
  - 'http://advair1.com/]advair'
  - 'http://suhagra2020.com/]suhagra'
  - 'http://indocinmed.com/]indocin'
  - 'http://acyclovirzov.com/]where'
  - 'http://antabusedsuf.com/]antabuse'
  - 'http://lasix.us.com/]generic'
  - 'http://sildalis365.us.com/]sildalis'
  - 'https://нериелтор.рф/krasnoyarsk-prodazha/prodam-treh-komnatnuyu-kvartiru/1-2-7%3E%D0%BA%D1%83%D0%BF%D0%B8%D1%82%D1%8C'
  - 'https://hydra-shop.org/'
  - pussy
  - 'https://cutt.us/ass2020'
  - 'http://valtrexx.com/]valtrex'
  - 'Вам перевод'
  - 'https://tinyurl.com'
include_default_list: '1'
webform_list:
  - contact
