content_type_breadcrumb:
  type_app: 'main:menu_link_content:e9c65de2-964b-4d89-8051-7f59ff201351'
  type_article: 'main:menu_link_content:a92b4794-19e1-465f-847c-5f1d9620ba37'
  type_commitment: ''
  type_consultation: ''
  type_external: ''
  type_idea: 'main:menu_link_content:63a1b52e-2a34-45ee-a853-a53185c97947'
  type_landing_page: ''
  type_page: ''
  type_suggested_dataset: 'main:menu_link_content:cd47ab77-a418-46c6-8888-e2c83071358c'
  type_webform: ''
  view_pd_core_ati: null
  view_pd_core_ati_details: 'main:menu_link_content:703d982b-078a-4730-8fca-1aaeeefa1c83'
  view_pd_core_contracts_details: 'main:menu_link_content:866f23ae-722e-461d-bc29-b574003b3305'
  view_pd_core_grants_details: 'main:menu_link_content:028b0675-1dfc-401e-bd8c-82b1df82c861'
  view_pd_core_reclassification_details: 'main:menu_link_content:ec2b9da2-56d6-413c-9675-4693402201c1'
