content_type_breadcrumb:
  type_app: 'main:menu_link_content:e9c65de2-964b-4d89-8051-7f59ff201351'
  type_article: 'main:menu_link_content:a92b4794-19e1-465f-847c-5f1d9620ba37'
  type_commitment: ''
  type_consultation: ''
  type_external: ''
  type_idea: 'main:menu_link_content:63a1b52e-2a34-45ee-a853-a53185c97947'
  type_landing_page: ''
  type_page: ''
  type_suggested_dataset: 'main:menu_link_content:cd47ab77-a418-46c6-8888-e2c83071358c'
  type_webform: ''
